name = 'alt:V Server'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['js-module', 'js-bytecode-module', 'csharp-module']
resources = ['server', 'nameless']
debug = true

[voice]
streamingTickRate = 10
# The bitrate of the voice server
bitrate = 64000
# The secret for the external server (only needed when using externalHost)
# The secret must consist of numeric values only
externalSecret = 1216750979
# The external host address (leave 127.0.0.1, if voice-server is on same machine)
externalHost = "127.0.0.1"
# The external host port
externalPort = 7799
# The external host public address (should be the ip address of your server, not localhost!)
externalPublicHost = "192.168.0.9"
# The external host public port
externalPublicPort = 7798